### ISSUE TITLE
Build fails with cloned repository in current state

### ISSUE THREAD

**Issue by CanRanBan** [darklinkpower/PlayniteExtensionsCollection#691]
Cloning the repository and building the solution / all projects to potentially provide additional debugging info for future updates / fixes is not possible with the current repository state.

Steps to reproduce:
1. `Clone using the web URL.`
2. Open `PlayniteExtensions.sln` with Visual Studio 2022 Community Edition.
3. Various errors during build attempt.

The following list of errors is reduced to display only the most important details.

Project `DatabaseCommon`:
- Missing reference:
  - Common\DatabaseCommon\LiteDbRepository.cs(2,7,2,15): error CS0246: "Playnite" not found.
  - Common\DatabaseCommon\LiteDbRepository.cs(3,7,3,20): error CS0246: "PluginsCommon" not found.
  - Common\DatabaseCommon\LiteDbRepository.cs(15,26,15,33): error CS0246: "ILogger" not found.
  - Common\DatabaseCommon\LiteDbRepository.cs(24,54,24,61): error CS0246: "ILogger" not found.

Project `EventsCommon`:
- Target Framework mismatch: .NET Framework is set to 4.7.2 instead of 4.6.2 used by Playnite

Project `GenericEntityJsonRepository`:
- Target Framework mismatch: .NET Framework is set to 4.7.2 instead of 4.6.2 used by Playnite
- Faulty reference:
  - Assembly "Playnite.SDK, Version=6.11.0.0, Culture=neutral, processorArchitecture=MSIL" not found.
    - Line 36 `HintPath` in `GenericEntityJsonRepository.csproj` does not point to the `packages` folder.
    - Adding `..\` at the beginning with the following result fixes this:
    - `<HintPath>..\..\packages\PlayniteSDK.6.11.0\lib\net462\Playnite.SDK.dll</HintPath>`

Project `PlayniteUtilitiesCommon`:
- Missing reference:
  - Common\PlayniteUtilitiesCommon\PlayniteUtilities.cs(11,22,11,30): error CS0234: "Controls" in "System.Windows" not available.
  - Common\PlayniteUtilitiesCommon\PlayniteUtilities.cs(12,22,12,27): error CS0234: "Media" in "System.Windows" not available.
  - Common\PlayniteUtilitiesCommon\PlayniteUtilities.cs(342,72,342,84): error CS0246: "FilterPreset" not found.

Project `PluginsCommon`:
- Missing reference:
  - Common\PluginsCommon\Behaviors\HoverPopupBehavior.cs(1,17,1,21): error CS0234: "Xaml" in "Microsoft" not available.
  - Common\PluginsCommon\Behaviors\ScrollIntoViewBehavior.cs(1,17,1,21): error CS0234: "Xaml" in "Microsoft" not available.
  - Common\PluginsCommon\Converters\ConvertersUtilities.cs(8,28,8,35): error CS0234: "Imaging" in "System.Windows.Media" not available.
  - Common\PluginsCommon\Converters\ImagePathToBitmapImageConverter.cs(9,28,9,35): error CS0234: "Imaging" in "System.Windows.Media" not available.
  - Common\PluginsCommon\Converters\ImagePathToBitmapImageWithCacheConverter.cs(8,28,8,35): error CS0234: "Imaging" in "System.Windows.Media" not available.
  - Common\PluginsCommon\Converters\ImagePathToBitmapImageWithCacheConverter.cs(9,7,9,21): error CS0246: "TemporaryCache" not found.
  - Common\PluginsCommon\Converters\ImageUriToBitmapImageConverter.cs(10,7,10,15): error CS0246: "FlowHttp" not found.
  - Common\PluginsCommon\Converters\ImageUriToBitmapImageConverter.cs(11,28,11,35): error CS0234: "Imaging" in "System.Windows.Media" not available.
  - Common\PluginsCommon\Converters\ImageUriToBitmapImageConverter.cs(12,7,12,21): error CS0246: "TemporaryCache" not found.
  - Common\PluginsCommon\Behaviors\ScrollIntoViewBehavior.cs(13,43,13,60): error CS0246: "Behavior<>" not found.
  - Common\PluginsCommon\Converters\ConvertersUtilities.cs(14,25,14,36): error CS0246: "BitmapImage" not found.
  - Common\PluginsCommon\Converters\ConvertersUtilities.cs(32,24,32,35): error CS0246: "BitmapImage" not found.
  - Common\PluginsCommon\Behaviors\HoverPopupBehavior.cs(10,39,10,65): error CS0246: "Behavior<>" not found.
  - Common\PluginsCommon\Behaviors\HoverPopupBehavior.cs(110,56,110,70): error CS0246: "MouseEventArgs" not found.
  - Common\PluginsCommon\Behaviors\HoverPopupBehavior.cs(117,56,117,70): error CS0246: "MouseEventArgs" not found.
  - Common\PluginsCommon\Behaviors\HoverPopupBehavior.cs(123,54,123,68): error CS0246: "MouseEventArgs" not found.
  - Common\PluginsCommon\Behaviors\HoverPopupBehavior.cs(129,54,129,68): error CS0246: "MouseEventArgs" not found.
  - Common\PluginsCommon\Converters\ImageUriToBitmapImageConverter.cs(20,33,20,66): error CS0246: "CacheManager<,>" not found.
  - Common\PluginsCommon\Converters\ImageUriToBitmapImageConverter.cs(20,54,20,65): error CS0246: "BitmapImage" not found.
  - Common\PluginsCommon\Converters\ImagePathToBitmapImageWithCacheConverter.cs(15,33,15,66): error CS0246: "CacheManager<,>" not found.
  - Common\PluginsCommon\Converters\ImagePathToBitmapImageWithCacheConverter.cs(15,54,15,65): error CS0246: "BitmapImage" not found.
  - Various files including Common\PluginsCommon\PluginUserControlBase.cs(21,51,21,68): error CS0012: "UIElement" defined in assembly without reference. Add reference to "PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".

Project `ProtobufUtilities`:
- Target Framework mismatch: .NET Framework is set to 4.7.2 instead of 4.6.2 used by Playnite
- Faulty reference:
  - Assembly "protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67, processorArchitecture=MSIL" not found.
    - Line 36 `HintPath` in `ProtobufUtilities.csproj` does not point to the `packages` folder.
    - Adding `..\` at the beginning with the following result fixes this:
    - `<HintPath>..\..\packages\protobuf-net.2.4.4\lib\net40\protobuf-net.dll</HintPath>`

Project `TemporaryCache`:
- Missing reference:
  - Common\TemporaryCache\CacheManager.cs(2,7,2,15): error CS0246: "Playnite" not found.
  - Common\TemporaryCache\CacheManager.cs(9,22,9,31): error CS0234: "Threading" in "System.Windows" not available.
  - Common\TemporaryCache\CacheManager.cs(16,33,16,40): error CS0246: "ILogger" not found.
  - Common\TemporaryCache\CacheManager.cs(19,26,19,41): error CS0246: "DispatcherTimer" not found.

Project `ThrottlerSharp`:
- Target Framework mismatch: .NET Framework is set to 4.7.2 instead of 4.6.2 used by Playnite

Project `WebViewCore`:
- Target Framework mismatch: .NET Framework is set to 4.7.2 instead of 4.6.2 used by Playnite
- Missing reference:
  - error MC6000: Project file needs to include reference to .NET Framework assemblies: "WindowsBase, PresentationCore, PresentationFramework".
- Reference to file not included in repository:
  - CSC : error CS2001: source file "Common\PluginsCommon\Converters\IconPathToImageSourceConverter.cs" not found.

Projects inside `Generic` and `Generic.Tests` were omitted.

Project `VNDBNexus`:
- Target Framework mismatch: .NET Framework is set to 4.7.2 instead of 4.6.2 used by Playnite

Projects inside `Metadata.Tests` were omitted.

**Comment by darklinkpower** [comment]
Most reference issues for all common projects are to be expected; These projects are not meant to be build or used directly, they are used in extension projects by referencing all their files as links rather than using full project references. The common libraries can be unloaded like this and ignored.

<img width="531" height="833" alt="Image" src="https://github.com/user-attachments/assets/86268132-9e4e-4905-9a14-fe3e65a37d4f" />

When doing that, all references are correctly resolved inside the extension projects themselves. The reason for doing it this way is because Playnite uses the old .NET framework, which doesn't support loading different versions of the same library and would cause crashes if I updated any common project and caused different plugins to use different versions of them. This is the safe way to do it until Playnite moves on to newer .NET that don't have this issue.

**Comment by CanRanBan** [comment]
Is there a reason to use `.csproj` instead of `.shproj`?
The second project type is intended for projects not meant to be build on their own.

**Comment by darklinkpower** [comment]
> Is there a reason to use `.csproj` instead of `.shproj`?
> The second project type is intended for projects not meant to be build on their own.

To be honest I didn't know of the existence of shproj, as an amateur hobbyist my knowledge is very limited and there are a ton of things that I don't know. I just looked it up and it looks like a very useful way of working in some scenarios, thanks for sharing about it.
